package com.example.multithreading.model;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "kafka_events")
@Data
public class AccountEvent {
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /*
        *  @GeneratedValue(strategy = GenerationType.IDENTITY)
        •	Configures the id field to be auto-generated by the database.
        •	Uses IDENTITY strategy, meaning the database will automatically generate
        *   the primary key (commonly used with auto-increment fields in MySQL, PostgreSQL, etc.).
        *
        *  @Id
        •	Specifies the primary key of the entity.
        * */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Auto-generates the account id
    private Long id;

    private String message;


}
