package com.example.multithreading.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Entity
@Data
public class Account {
    /*
    *  @GeneratedValue(strategy = GenerationType.IDENTITY)
	•	Configures the id field to be auto-generated by the database.
	•	Uses IDENTITY strategy, meaning the database will automatically generate
	*   the primary key (commonly used with auto-increment fields in MySQL, PostgreSQL, etc.).
	*
	*  @Id
	•	Specifies the primary key of the entity.
    * */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Auto-generates the account id
    private Long id;

    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
